### ISSUE TITLE
 Date Scheduling Issue

### ISSUE THREAD

**Issue by alysha9110** [ThaddeusJiang/Projectify#11]
**Description**
I'm experiencing an issue with the Projectify plugin while using the latest version of TiddlyWiki (5.3.5). When I attempt to schedule tasks, the dates are not being set correctly:

1. Clicking "Today" schedules tasks for tomorrow.
2. Clicking "Tomorrow" schedules tasks for two days later.

It seems that the plugin may not be reading the time zone correctly, which could be causing this discrepancy. Any help in resolving this issue would be appreciated =)

**Environment**
TiddlyWiki Version: 5.3.5
Browser: Vivaldi (6.8.3381.53), also tested on Chrome and Edge
I'm staying in NZ, so am in the GMT+12 time zone

**Steps to Reproduce**

1. Open TiddlyWiki with the Projectify plugin.
2. Attempt to schedule a task for "Today".
3. Observe that the task is scheduled for tomorrow.
4. Attempt to schedule a task for "Tomorrow".
5. Observe that the task is scheduled for two days later.

**Expected Behavior**
Tasks should be scheduled for the correct dates based on the selected options.

**Comment by ThaddeusJiang** [comment]
@alysha9110 Thank you for feedback, I will confirm it later.

**Comment by ThaddeusJiang** [comment]
Hi @alysha9110 
I have fixed the issue, you can confirm it in https://projectify-git-fix-date-scheduling-thaddeus-jiangs-projects.vercel.app/demo.html

PR: #12
