### ISSUE TITLE
add todo's at the top of the todo-list?

### ISSUE THREAD

**Issue by coderofsalvation** [ThaddeusJiang/Projectify#5]
Todo's are added to the bottom by default, which makes it very hard to move them to the top if the list of todo's is long, especially on mobile.
In most cases, newly added todo's are highest prio in case..so is there a way to change this behaviour?
I was poking around, but I couldn't really figure out where the add-to-bottom behaviour is programmed...

any idea?

**Comment by ThaddeusJiang** [comment]
@coderofsalvation Yes, I think it is good idea.

**Comment by ThaddeusJiang** [comment]
@coderofsalvation Thank you for feedback, I have pushed a improvement, could you confirm it is ok to you? #9
