### ISSUE TITLE
Category name containing space are displayed twice in project list

### ISSUE THREAD

**Issue by chept** [ThaddeusJiang/Projectify#6]
See this demo : https://projectify-tests.tiddlyhost.com/

The "Category 2" is displayed in two columns.
It happens to every category containing a space in name.

For the moment I work around without using space in names, I am not powerful enough to modify this behaviour.

Thank you for supporting this awesome project !

**Comment by chept** [comment]
Eventually I found a way to fix this !

In  `$:/plugins/nico/projectify/ui/dashboard/ProjectListItem` I just quoted the filter :

`<$list filter=<<category>> variable="ignore">`
becomes
`<$list filter="<<category>>" variable="ignore">`

I don't know if this is THE way but it works for me !

**Comment by ThaddeusJiang** [comment]
@chept Thank you for feedback, I will confirm it.

**Comment by ThaddeusJiang** [comment]
@chept Thank you for your code, it works.
