### ISSUE TITLE
Add level of completion to single task

### ISSUE THREAD

**Issue by hitam4450** [ThaddeusJiang/Projectify#8]
Hi,

i just installed Projectify to my Business Wiki and I am very happy with it.  Many thanks for your great work and achievement.
However, there are always ways to improve or add additional features to the project. 

What I am missing is a slider to mark e.g. the percentage of completion to single tasks, because you are not always in a position to complete a single task all at once, especially when you get interrupted or restart after e.g. sickness or absence.

Best regards, hitam4450

**Comment by ThaddeusJiang** [comment]
Hi @hitam4450 
Thank you for feedback.

Can the Project Subtask feature meet your requirements? As shown

https://github.com/ThaddeusJiang/Projectify/assets/17308201/9c003b75-d79c-40ff-ade6-fd765ebdd2c7
